SHOPPER/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SHOPPER.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

SHOPPER/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SHOPPER.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

SHOPPER/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SHOPPER.Models;
namespace SHOPPER.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        ShopperEntities db = new ShopperEntities();
        public ActionResult Index()
        {
            List<SanPham> l = db.SanPhams.Where(x => (x.daDuyet == true)).OrderByDescending(x => x.ngayDang).Take(8).ToList<SanPham>();
            ViewData["layspmoi"] = l;
            return View();
        }
        [HttpPost]
        public ActionResult addToCart(string maspCart)
        {
            //Lấy giỏ hàng từ session
            CartShop gh = Session["gioHang"] as CartShop;
            //Thêm vào giỏ hàng
            gh.addItem(maspCart);
            //cập nhật lại giỏ hàng
            Session["gioHang"] = gh;
            return RedirectToAction("Index");
        }       
        
    }
}

SHOPPER/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SHOPPER.Models;
namespace SHOPPER.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        ShopperEntities db = new ShopperEntities();
        List<SanPham> sp = new List<SanPham>();
        private static string ml;
        [HttpGet]
        public ActionResult Index(string maloai, string s)
        {            
            ml = maloai;
            DemSPSale();
            if (maloai != null)
            {
                //sp = db.SanPhams.Where(x => (x.daDuyet == true) && (x.maLoai.Equals(maloai))).ToList();
                //ViewBag.spTheoLoai = sp;
                if (s == "0")
                {
                    sp = db.SanPhams.Where(x => (x.daDuyet == true) && (x.maLoai.Equals(maloai))).OrderByDescending(z => z.giaBan).ToList();
                    ViewBag.spTheoLoai = sp;
                }
                else if (s == "1")
                {
                    sp = db.SanPhams.Where(x => (x.daDuyet == true) && (x.maLoai.Equals(maloai))).OrderBy(z => z.giaBan).ToList();
                    ViewBag.spTheoLoai = sp;
                }
                else if (s == null)
                {
                    sp = db.SanPhams.Where(x => (x.daDuyet == true) && (x.maLoai.Equals(maloai))).ToList();
                    ViewBag.spTheoLoai = sp;
                }
            }
            else
            {
                //sp = db.SanPhams.Where(x => (x.daDuyet == true)).ToList();
                //ViewBag.spTheoLoai = sp;
                if (s == "0")
                {
                    sp = db.SanPhams.Where(x => (x.daDuyet == true)).OrderByDescending(z => z.giaBan).ToList();
                    ViewBag.spTheoLoai = sp;
                }
                else if (s == "1")
                {
                    sp = db.SanPhams.Where(x => (x.daDuyet == true)).OrderBy(z => z.giaBan).ToList();
                    ViewBag.spTheoLoai = sp;
                }
                else if (s == null)
                {
                    sp = db.SanPhams.Where(x => (x.daDuyet == true)).ToList();
                    ViewBag.spTheoLoai = sp;
                }
            }
            return View();
        }
        [HttpPost]
        public ActionResult SapXep(string sx)
        {           
            return RedirectToAction("Index", new {maloai = ml, s = sx });
        }
        [HttpPost]
        public ActionResult addToCart(string maspCart)
        {
            //Lấy giỏ hàng từ session
            CartShop gh = Session["gioHang"] as CartShop;
            //Thêm vào giỏ hàng
            gh.addItem(maspCart);
            //cập nhật lại giỏ hàng
            Session["gioHang"] = gh;
            return RedirectToAction("Index");
        }
        //Phương thức tìm kiếm sản phẩm
        [HttpPost]
        public ActionResult Search(string text)
        {
            ShopperEntities db = new ShopperEntities();
            if (!String.IsNullOrEmpty(text))
            {
                List<SanPham> l = db.SanPhams.Where(x => (x.tenSP.Contains(text)) && (x.daDuyet == true)).ToList<SanPham>();
                ViewData["dstimkiem"] = l;
            }
            DemSPSale();
            return View();
        }
        //Phương thức xem sản phẩm đang giảm giá
        [HttpGet]
        public ActionResult OnSale()
        {
            ShopperEntities db = new ShopperEntities();
            List<SanPham> l = db.SanPhams.Where(x => (x.daDuyet == true) && (x.giamGia > 0)).ToList<SanPham>();
            ViewData["dssale"] = l;
            DemSPSale();
            return View();
        }
        private void DemSPSale()
        {
            ShopperEntities db = new ShopperEntities();
            List<SanPham> l = db.SanPhams.Where(x => (x.daDuyet == true) && (x.giamGia > 0)).ToList<SanPham>();
            ViewData["demspsale"] = l.Count();
        }
    }
}

SHOPPER/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using SHOPPER.Models;
@{
    Common layout = (Common)HttpContext.Current.Application["all"];
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    @Styles.Render("~/bundles/css1")

</head>
<body>
    <div class="site-wrap">
        <header class="site-navbar" role="banner">
            <div class="site-navbar-top">
                <div class="container">
                    <div class="row align-items-center">

                        <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                            @using (Html.BeginForm("Search", "Product", FormMethod.Post))
                            {   
                                <div class="form-inline">
                                    <span class="icon icon-search2"></span>
                                    @Html.TextBox("text", "", new { @class = "form-control border-0", @placeholder = "Tìm kiếm sản phẩm" })
                                </div>                                   
                            }                            
                        </div>

                        <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                            <div class="site-logo">
                                <a href='@Url.Action("Index", "Default")' class="js-logo-clone">Shoppers</a>
                            </div>
                        </div>

                        <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                            <div class="site-top-icons">
                                <ul>
                                    <li><a href='@Url.Action("Index","Login")'><span class="icon icon-person"></span></a></li>
                                    <li>
                                        <a href='@Url.Action("Index","Cart")' class="site-cart">
                                            <span class="icon icon-shopping_cart"></span>
                                        </a>
                                    </li>
                                    <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                                </ul>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <nav class="site-navigation text-right text-md-center" role="navigation">
                <div class="container">
                    <ul class="site-menu js-clone-nav d-none d-md-block">
                        <li>
                            @Html.ActionLink("TRANG CHỦ", "Index", "Default")
                        </li>
                        <li>
                            @Html.ActionLink("VỀ CHÚNG TÔI", "Index", "About")

                        </li>
                        <li class="has-children">
                            @Html.ActionLink("SẢN PHẨM", "Index", "Product")
                            <ul class="dropdown">
                                @foreach (LoaiSP i in layout.loaisanpham())
                                {
                                    <li><a href='@Url.Action("Index","Product", new {maloai = i.maLoai })'>@i.tenLoai</a></li>
                                }
                            </ul>
                        </li>
                        <li>
                            @Html.ActionLink("BÀI VIẾT", "Index", "Articles")
                        </li>
                        <li>
                            @Html.ActionLink("LIÊN HỆ", "Index", "Contact")
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        @RenderBody()

        <footer class="site-footer border-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 mb-5 mb-lg-0">
                        <div class="row">
                            <div class="col-md-6 col-lg-4">
                                <h3 class="footer-heading mb-4">Chính sách</h3>
                                <ul class="list-unstyled">
                                    <li><a href="#">Chính sách đổi hàng</a></li>
                                    <li><a href="#">Chính sách vận chuyển</a></li>
                                    <li><a href="#">Chính sách hoàn tiền</a></li>
                                    <li><a href="#">Chính sách bảo mật</a></li>
                                </ul>
                            </div>
                            <div class="col-md-6 col-lg-4">
                                <h3 class="footer-heading mb-4">Thông tin</h3>
                                <ul class="list-unstyled">
                                    <li><a href="#">Giới thiệu</a></li>
                                    <li><a href="#">Liên hệ</a></li>
                                    <li><a href="#">Đối tác</a></li>
                                    <li><a href="#">Tuyển dụng</a></li>
                                </ul>
                            </div>
                            <div class="col-md-6 col-lg-4">
                                <h3 class="footer-heading mb-4">FAQ</h3>
                                <ul class="list-unstyled">
                                    <li><a href="#">Kiểm tra thông tin đơn hàng</a></li>
                                    <li><a href="#">Thanh toán và vận chuyển</a></li>
                                    <li><a href="#">Câu hỏi thường gặp</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
                        <h3 class="footer-heading mb-4">Xem thêm</h3>
                        <a href='@Url.Action("OnSale", "Product")' class="block-6">
                            <img src="~/asset/images/nam-moi-2023.png" alt="Image placeholder" class="img-fluid rounded mb-4">
                            <h3 class="font-weight-light  mb-0">Tìm đồ mặc Tết?</h3>
                        </a>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="block-5 mb-5">
                            <h3 class="footer-heading mb-4">Liên Hệ</h3>
                            <ul class="list-unstyled">
                                <li class="phone"><a href="tel://23923929210">0345183573</a></li>
                                <li class="email">Khoav538@gmail.com</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!--<div class="row pt-5 mt-5 text-center">
                    <div class="col-md-12">
                        <p>-->
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            <!--Copyright &copy;
                            <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" class="text-primary">Colorlib</a>-->
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <!--</p>
                    </div>
                </div>-->
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/script1")


</body>
</html>