SHOPPER/Controllers/ArticleDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SHOPPER.Models;
namespace SHOPPER.Controllers
{
    public class ArticleDetailController : Controller
    {
        // GET: ArticleDetail
        public ActionResult Index(string mabaiviet)
        {
            ShopperEntities db = new ShopperEntities();
            BaiViet bv = db.BaiViets.Where(x => x.maBV == mabaiviet).First<BaiViet>();
            ViewBag.ctbv = bv;
            return View();
        }
    }
}

SHOPPER/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SHOPPER.Models;
namespace SHOPPER.Controllers
{
    public class ArticlesController : Controller
    {
        // GET: Articles
        public ActionResult Index()
        {
            ShopperEntities db = new ShopperEntities();
            List<BaiViet> l = db.BaiViets.Where(x => x.daDuyet == true).ToList<BaiViet>();
            ViewData["ltcbv"] = l;
            return View();
        }
    }
}

SHOPPER/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SHOPPER.Models;
namespace SHOPPER.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        ShopperEntities db = new ShopperEntities();
        public ActionResult Index()
        {
            List<SanPham> l = db.SanPhams.Where(x => (x.daDuyet == true)).OrderByDescending(x => x.ngayDang).Take(8).ToList<SanPham>();
            ViewData["layspmoi"] = l;
            return View();
        }
        [HttpPost]
        public ActionResult addToCart(string maspCart)
        {
            //Lấy giỏ hàng từ session
            CartShop gh = Session["gioHang"] as CartShop;
            //Thêm vào giỏ hàng
            gh.addItem(maspCart);
            //cập nhật lại giỏ hàng
            Session["gioHang"] = gh;
            return RedirectToAction("Index");
        }       
        
    }
}

SHOPPER/Views/ArticleDetail/Index.cshtml
@using SHOPPER.Models
@{
    ViewBag.Title = "SHOPPER - ";
    BaiViet xem = ViewBag.ctbv;
}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a href='@Url.Action("Index","Default")'>Trang chủ</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">@xem.tenBV</strong></div>
        </div>
    </div>
</div>
<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-black text-center">@xem.tenBV</h2>
            </div>
            <div class="col-md-12">
                <p class="small">@xem.TaiKhoan1.hoDem @xem.TaiKhoan1.tenTV @String.Format("{0:| dd/MM/yyyy}", xem.ngayDang)</p>
            </div>

            @*<div class="col-md-12">
                    <img src="@xem.hinhDD" alt="Image" class="img-fluid">
                </div>*@
            <div class="col-md-10 text-black">
                @Html.Raw(xem.noiDung)
            </div>
            <div class="col-md-12 text-center mt-5">
                <a href='@Url.Action("Index","Articles")' class="btn btn-primary ">Trở về</a>

            </div>
        </div>
    </div>
</div>