SHOPPER/Areas/Admin/Controllers/orderManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SHOPPER.Models;
namespace SHOPPER.Areas.Admin.Controllers
{
    public class orderManagementController : Controller
    {
        // GET: Admin/orderManagement
        private static ShopperEntities db = new ShopperEntities();
        private static bool daDuyet;
        public ActionResult Index()
        {
            List<DonHang> l =   db.DonHangs.Where(x => (x.daKichHoat == false) && (x.ghiChu == null)).
                                OrderByDescending(x => x.ngayDat).ToList<DonHang>();
            ViewData["dsdh"] = l;
            return View();
        }
        //Phương thức xoá đơn hàng
        [HttpPost]
        public ActionResult Delete(string dhXoa)
        {
            //Tìm đến bài viết cần xoá
            try
            {
                foreach(CtDonHang i in db.CtDonHangs)
                {
                    if (i.soDH == dhXoa)
                    {
                        db.CtDonHangs.Remove(i);
                    }
                }
            } catch { }
            DonHang x = db.DonHangs.Find(dhXoa);
            //Xoá
            db.DonHangs.Remove(x);
            //cập nhật dữ liệu lại cho database
            db.SaveChanges();
            //Hiển thị dữ liệu trên View           
            return RedirectToAction("DHDaHuy");
        }
        //Phương thức và View cho đơn hàng đã huỷ
        public ActionResult DHDaHuy()
        {
            List<DonHang> l = db.DonHangs.Where(z => (z.daKichHoat == false) && (z.ghiChu == "Đã huỷ")).ToList<DonHang>();
            ViewData["dsdhdh"] = l;
            return View();
        }
        [HttpPost]
        public ActionResult UnActive(string dhKH)
        {
            DonHang x = db.DonHangs.Find(dhKH);
            x.daKichHoat = false;
            x.ghiChu = "Đã huỷ";
            db.SaveChanges();           
            return RedirectToAction("DHDaHuy");
        }
        //Phương thức và View cho đơn hàng đang giao
        public ActionResult Active()
        {           
            List<DonHang> l = db.DonHangs.Where(z => (z.daKichHoat == true) && (z.ghiChu == "Đang giao")).ToList<DonHang>();
            ViewData["dsdhdg"] = l;
            return View();
        }
        [HttpPost]
        public ActionResult ActiveControl(string dhKH)
        {
            DonHang x = db.DonHangs.Find(dhKH);
            x.daKichHoat = true;
            x.ngayGH = DateTime.Now;
            x.ghiChu = "Đang giao";
            db.SaveChanges();
            return RedirectToAction("Active");
        }
        //PHương thức và View cho đơn hàng đã hoàn thành
        public ActionResult finish()
        {
            List<DonHang> l = db.DonHangs.Where(z => (z.daKichHoat == true) && (z.ghiChu == "Hoàn thành")).ToList<DonHang>();
            ViewData["dsdhht"] = l;
            return View();
        }
        public ActionResult finishControl(string dhht)
        {
            DonHang x = db.DonHangs.Find(dhht);
            x.daKichHoat = true;
            x.ghiChu = "Hoàn thành";
            db.SaveChanges();
            return RedirectToAction("finish");
        }
    }
}

SHOPPER/Areas/Admin/Views/orderManagement/Active.cshtml
@using SHOPPER.Models
@{
    ViewBag.Title = "SHOPER - ADMIN - Quản lí đơn hàng";
}


<section class="content-header">
    <h1>
        Danh sách đơn hàng
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Trang chủ</a></li>
        <li><a href="#">Danh sách đơn hàng</a></li>
        <li class="active">Danh sách đơn hàng đang giao</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Danh sách đơn hàng đang giao</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Mã đơn hàng</th>
                                <th>Tên khách hàng</th>
                                <th>Ngày đặt</th>
                                <th>Ngày giao</th>
                                <th>Địa chỉ</th>
                                <th>Ghi chú</th>
                                <th>Nhóm lệnh</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                List<DonHang> l = ViewData["dsdhdg"] as List<DonHang>;
                                foreach (DonHang i in l)
                                {
                                    <tr>
                                        <td>@i.soDH</td>
                                        <td>@i.KhachHang.tenKH</td>
                                        <td>@i.ngayDat</td>
                                        <td>@i.ngayGH</td>
                                        <td>@i.diaChiGH</td>
                                        <td>@i.ghiChu</td>
                                        <td>
                                            <div class="btn-group">
                                                <a href='@Url.Action("Index", "orderSingle", new {madh = i.soDH })' class="btn btn-success mx-auto">Chi tiết</a>
                                                @using (Html.BeginForm("UnActive", "orderManagement", FormMethod.Post))
                                                {
                                                    <input type="hidden" name="dhKH" value="@i.soDH.Trim()" />
                                                    <button class="btn btn-danger">Huỷ đơn hàng</button>
                                                }
                                                @using (Html.BeginForm("finishControl", "orderManagement", FormMethod.Post))
                                                {
                                                    <input type="hidden" name="dhht" value="@i.soDH.Trim()" />
                                                    <button class="btn btn-primary">Hoàn thành</button>
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

SHOPPER/Areas/Admin/Views/orderManagement/DHDaHuy.cshtml
@using SHOPPER.Models
@{
    ViewBag.Title = "SHOPER - ADMIN - Quản lí đơn hàng";
}


<section class="content-header">
    <h1>
        Danh sách đơn hàng
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Trang chủ</a></li>
        <li><a href="#">Danh sách đơn hàng</a></li>
        <li class="active">Danh sách đơn hàng đã huỷ</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Danh sách đơn hàng đã huỷ</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Mã đơn hàng</th>
                                <th>Tên khách hàng</th>
                                <th>Ngày đặt</th>
                                <th>Ngày giao</th>
                                <th>Địa chỉ</th>
                                <th>Ghi chú</th>
                                <th>Nhóm lệnh</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                List<DonHang> l = ViewData["dsdhdh"] as List<DonHang>;
                                foreach (DonHang i in l)
                                {
                                    <tr>
                                        <td>@i.soDH</td>
                                        <td>@i.KhachHang.tenKH</td>
                                        <td>@i.ngayDat</td>
                                        <td>@i.ngayGH</td>
                                        <td>@i.diaChiGH</td>
                                        <td>@i.ghiChu</td>
                                        <td>
                                            <div class="btn-group">
                                                <a href='@Url.Action("Index", "orderSingle", new {madh = i.soDH })' class="btn btn-success mx-auto">Chi tiết</a>
                                                @using (Html.BeginForm("ActiveControl", "orderManagement", FormMethod.Post))
                                                {
                                                    <input type="hidden" name="dhKH" value="@i.soDH.Trim()" />
                                                    <button class="btn btn-primary">Giao lại</button>
                                                }
                                                @using (Html.BeginForm("Delete", "orderManagement", FormMethod.Post))
                                                {
                                                    <input type="hidden" name="dhXoa" value="@i.soDH.Trim()" />
                                                    <button class="btn btn-danger">Xoá</button>
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

SHOPPER/Areas/Admin/Views/orderManagement/Index.cshtml
@using SHOPPER.Models
@{
    ViewBag.Title = "SHOPER - ADMIN - Quản lí đơn hàng";
}


<section class="content-header">
    <h1>
        Danh sách đơn hàng
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Trang chủ</a></li>
        <li><a href="#">Danh sách đơn hàng</a></li>
        <li class="active">Danh sách đơn hàng chờ duyệt</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Danh sách đơn hàng chờ duyệt</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Mã đơn hàng</th>
                                <th>Tên khách hàng</th>
                                <th>Ngày đặt</th>
                                <th>Địa chỉ</th>
                                <th>Ghi chú</th>
                                <th>Nhóm lệnh</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                List<DonHang> l = ViewData["dsdh"] as List<DonHang>;
                                foreach (DonHang i in l)
                                {
                                    <tr>                                       
                                        <td>@i.soDH</td>
                                        <td>@i.KhachHang.tenKH</td>
                                        <td>@i.ngayDat</td>
                                        <td>@i.diaChiGH</td>
                                        <td>@i.ghiChu</td>
                                        <td>
                                            <div class="btn-group">
                                                <a href='@Url.Action("Index", "orderSingle", new { madh = i.soDH })' class="btn btn-success mx-auto">Chi tiết</a>
                                                @using (Html.BeginForm("ActiveControl", "orderManagement", FormMethod.Post))
                                                {
                                                    <input type="hidden" name="dhKH" value="@i.soDH.Trim()" />
                                                    <button class="btn btn-primary">Giao hàng</button>
                                                }
                                                @using (Html.BeginForm("UnActive", "orderManagement", FormMethod.Post))
                                                {
                                                    <input type="hidden" name="dhKH" value="@i.soDH.Trim()" />
                                                    <button class="btn btn-danger">Huỷ đơn hàng</button>
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>                        
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

SHOPPER/Areas/Admin/Views/orderManagement/finish.cshtml
@using SHOPPER.Models
@{
    ViewBag.Title = "SHOPER - ADMIN - Quản lí đơn hàng";
}


<section class="content-header">
    <h1>
        Danh sách đơn hàng
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Trang chủ</a></li>
        <li><a href="#">Danh sách đơn hàng</a></li>
        <li class="active">Danh sách đơn hàng đã hoàn thành</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Danh sách đơn hàng đã hoàn thành</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Mã đơn hàng</th>
                                <th>Tên khách hàng</th>
                                <th>Ngày đặt</th>
                                <th>Ngày giao</th>
                                <th>Địa chỉ</th>
                                <th>Ghi chú</th>
                                <th>Nhóm lệnh</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                List<DonHang> l = ViewData["dsdhht"] as List<DonHang>;
                                foreach (DonHang i in l)
                                {
                                    <tr>
                                        <td>@i.soDH</td>
                                        <td>@i.KhachHang.tenKH</td>
                                        <td>@i.ngayDat</td>
                                        <td>@i.ngayGH</td>
                                        <td>@i.diaChiGH</td>
                                        <td>@i.ghiChu</td>
                                        <td>
                                            <div class="btn-group">
                                                <a href='@Url.Action("Index", "orderSingle", new {madh = i.soDH })' class="btn btn-success mx-auto">Chi tiết</a>
                                                @using (Html.BeginForm("Delete", "orderManagement", FormMethod.Post))
                                                {
                                                    <input type="hidden" name="dhXoa" value="@i.soDH.Trim()" />
                                                    <button class="btn btn-danger">Xoá</button>
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>